In [ ]:
# 1.Write a program to take a 2d numpy from the user and Check Whether the given 2D NumPy array is symmetric or not.

In [ ]:
# 2.Write a Program to find the sum of the diagonal elements of a square 2D NumPy array.

In [3]:
import numpy as np

def sum_of_diagonal_elements(array):
    
    if len(array.shape) != 2 or array.shape[0] != array.shape[1]:
        return None
    

    size = array.shape[0]
   
    diagonal_sum = np.trace(array)
    
    return diagonal_sum


array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[2, 4],
                   [6, 8]])


result1 = sum_of_diagonal_elements(array1)
if result1 is not None:
    print("Sum of diagonal elements (array1):", result1)
else:
    print("Input array1 is not a square matrix.")


result2 = sum_of_diagonal_elements(array2)
if result2 is not None:
    print("Sum of diagonal elements (array2):", result2)
else:
    print("Input array2 is not a square matrix.")


Sum of diagonal elements (array1): 15
Sum of diagonal elements (array2): 10


In [ ]:
# 3. Write a Program to rotate a given 2D NumPy array by 90 degrees anti-clockwise.

In [4]:
import numpy as np

def rotate_90_anticlockwise(array):
  
    rotated_array = np.flipud(array.T)
    return rotated_array


array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])


rotated_array1 = rotate_90_anticlockwise(array1)
print("Rotated Array 1 (90 degrees anti-clockwise):\n", rotated_array1)

rotated_array2 = rotate_90_anticlockwise(array2)
print("Rotated Array 2 (90 degrees anti-clockwise):\n", rotated_array2)


Rotated Array 1 (90 degrees anti-clockwise):
 [[3 6 9]
 [2 5 8]
 [1 4 7]]
Rotated Array 2 (90 degrees anti-clockwise):
 [[2 4 6]
 [1 3 5]]


In [ ]:
#4.write a Program to find the largest element in each row of a 2D NumPy array.

In [5]:
import numpy as np

def find_largest_in_each_row(array):
   
    largest_elements = np.max(array, axis=1)
    return largest_elements


array1 = np.array([[1, 4, 7],
                   [2, 5, 8],
                   [3, 6, 9]])

array2 = np.array([[9, 2, 3],
                   [4, 8, 5],
                   [6, 1, 7]])

result1 = find_largest_in_each_row(array1)
print("Largest element in each row of array1:", result1)


result2 = find_largest_in_each_row(array2)
print("Largest element in each row of array2:", result2)


Largest element in each row of array1: [7 8 9]
Largest element in each row of array2: [9 8 7]


In [ ]:
#5 write a program to find the average of each column in a 2D NumPy array.

In [6]:
import numpy as np

def average_of_each_column(array):
    
    column_averages = np.mean(array, axis=0)
    return column_averages


array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[2, 4],
                   [6, 8]])


result1 = average_of_each_column(array1)
print("Average of each column for array1:", result1)

result2 = average_of_each_column(array2)
print("Average of each column for array2:", result2)


Average of each column for array1: [4. 5. 6.]
Average of each column for array2: [4. 6.]


In [ ]:
# 6. Write a program to count the number of occurrences of a specific value in a 2D NumPy array.

In [9]:
import numpy as np

def count_occurrences_2d_array(array, value):
   
    flattened_array = array.ravel()
    
 
    count = np.count_nonzero(flattened_array == value)
    
    return count


array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
value = 2
array1 = np.array([[2, 4, 6], [8, 2, 4], [2, 2, 2]])
value1 = 4

result = count_occurrences_2d_array(array, value)
print("Number of occurrences of", value, "in the array:", result)
result1 = count_occurrences_2d_array(array1, value1)
print("Number of occurrences of", value1, "in the array:", result1)


Number of occurrences of 2 in the array: 1
Number of occurrences of 4 in the array: 2


In [ ]:
#7. Write a Program to find the determinant of a 2x2 matrix represented as a NumPy array.


In [10]:
import numpy as np

def determinant_2x2_matrix(array):
   
    a = array[0, 0]
    b = array[0, 1]
    c = array[1, 0]
    d = array[1, 1]
    
 
    determinant_value = (a * d) - (b * c)
    
    return determinant_value

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[2, 5], [3, 7]])

determinant1 = determinant_2x2_matrix(array1)
determinant2 = determinant_2x2_matrix(array2)

print("Determinant of array1:", determinant1)
print("Determinant of array2:", determinant2)


Determinant of array1: -2
Determinant of array2: -1


In [ ]:
# 8. Write a program to pad a given 2D NumPy array with zeros around its borders.

In [11]:
import numpy as np

def pad_array_with_zeros(array):
 
    rows, cols = array.shape
    

    padded_array = np.pad(array, ((1, 1), (1, 1)), mode='constant', constant_values=0)
    
    return padded_array


array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[9, 8], [7, 6]])

padded_array1 = pad_array_with_zeros(array1)
padded_array2 = pad_array_with_zeros(array2)

print("Padded array 1:")
print(padded_array1)

print("\nPadded array 2:")
print(padded_array2)


Padded array 1:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 0 0 0 0]]

Padded array 2:
[[0 0 0 0]
 [0 9 8 0]
 [0 7 6 0]
 [0 0 0 0]]


In [ ]:
# 9. Write a program to find the index of the maximum element in a 2D NumPy array.

In [12]:
import numpy as np

def find_max_element_index(array):
   
    flat_index = np.argmax(array)  # Find the index of the maximum element in the flattened array

    max_index_2d = np.unravel_index(flat_index, array.shape)       
    # Convert the flattened index to 2D coordinates
    
    return max_index_2d


array1 = np.array([[1, 3, 5], [4, 9, 2], [8, 7, 6]])
array2 = np.array([[7, 2, 4], [5, 9, 8], [6, 3, 1]])

max_index1 = find_max_element_index(array1)
max_index2 = find_max_element_index(array2)

print("Index of maximum element in array 1:", max_index1)
print("Index of maximum element in array 2:", max_index2)


Index of maximum element in array 1: (1, 1)
Index of maximum element in array 2: (1, 1)


In [ ]:
# 10. Write a program to check if a given 2D NumPy array contains any duplicate rows.

In [13]:
import numpy as np

def contains_duplicate_rows(array):
    # Convert each row of the array into a tuple for hashing
    # Then, use set to check for duplicates
    seen_rows = set()
    
    for row in array:
        # Convert the row to a tuple to make it hashable
        row_tuple = tuple(row)
        
        # Check if the row_tuple has been seen before
        if row_tuple in seen_rows:
            return True
        else:
            seen_rows.add(row_tuple)
    
    return False


array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])

result1 = contains_duplicate_rows(array1)
result2 = contains_duplicate_rows(array2)

if result1:
    print("Output: Yes")
else:
    print("Output: No")

if result2:
    print("Output: Yes")
else:
    print("Output: No")


Output: No
Output: Yes
