In [ ]:
# 1.Write a program to calculate the alternate sum of elements in a 2d numpy array(start from 0)

In [8]:
import numpy as np

def altSum(arr):
    sumEle = 0
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if (i + j) % 2 == 0:
                sumEle += arr[i][j]
    return sumEle


row = int(input("Enter the number of rows: "))
col = int(input("Enter the number of columns: "))


arr = np.zeros((row, col), dtype=int)
print("Enter the elements row-wise:")


for i in range(row):
    for j in range(col):
        arr[i][j] = int(input(f"Element [{i}][{j}]: "))

# Calculate the alternate sum
sumEle = altSum(arr)
print("Alternate Sum:", sumEle)



Enter the number of rows:  3
Enter the number of columns:  3


Enter the elements row-wise:


Element [0][0]:  1
Element [0][1]:  2
Element [0][2]:  3
Element [1][0]:  4
Element [1][1]:  5
Element [1][2]:  6
Element [2][0]:  7
Element [2][1]:  8
Element [2][2]:  9


Alternate Sum: 25


In [ ]:
# 2. Write a program to find the all even numbers from the given 2d numpy array

In [11]:
import numpy as np

def get_user_input():
    rows = int(input("Enter the number of rows: "))
    arr = []
    for i in range(rows):
        row = list(map(int, input(f"Enter the numbers for row {i+1} separated by spaces: ").split()))
        arr.append(row)
    return np.array(arr)

def find_even_numbers(arr):
    return arr[arr % 2 == 0]


array = get_user_input()


even_numbers = find_even_numbers(array)


print("Even numbers in the array are:", even_numbers)


Enter the number of rows:  3
Enter the numbers for row 1 separated by spaces:  4
Enter the numbers for row 2 separated by spaces:  6
Enter the numbers for row 3 separated by spaces:  8


Even numbers in the array are: [4 6 8]


In [ ]:
# 3.  Write a program to find the all prime numbers from the given 2d numpy array

In [12]:
import numpy as np

def get_user_input():
    rows = int(input("Enter the number of rows: "))
    arr = []
    for i in range(rows):
        row = list(map(int, input(f"Enter the numbers for row {i+1} separated by spaces: ").split()))
        arr.append(row)
    return np.array(arr)

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

def find_prime_numbers(arr):
    prime_numbers = []
    for num in np.nditer(arr):
        if is_prime(num):
            prime_numbers.append(num)
    return np.array(prime_numbers)


array = get_user_input()


prime_numbers = find_prime_numbers(array)


print("Prime numbers in the array are:", prime_numbers)


Enter the number of rows:  3
Enter the numbers for row 1 separated by spaces:  2
Enter the numbers for row 2 separated by spaces:  5
Enter the numbers for row 3 separated by spaces:  6


Prime numbers in the array are: [2 5]


In [ ]:
# 4. WAP Generate a 5x5 numpy array of random integers and write a loop to find and print the maximum value in each row

In [13]:
import numpy as np


low = int(input("Enter the lowest possible integer: "))
high = int(input("Enter the highest possible integer: "))


arr = np.random.randint(low, high+1, size=(5, 5))

print("Generated 5x5 array:")
print(arr)


max_values = []
for row in arr:
    max_values.append(np.max(row))

print("Maximum values in each row:", max_values)


Enter the lowest possible integer:  3
Enter the highest possible integer:  8


Generated 5x5 array:
[[5 8 7 8 7]
 [7 3 3 7 6]
 [4 4 4 4 7]
 [5 3 5 5 4]
 [5 5 3 7 3]]
Maximum values in each row: [8, 7, 7, 5, 7]


In [ ]:
# 5. WAP to print the non-corner elements from the 2d numpy array

In [15]:
import numpy as np

def get_user_input():
    rows = int(input("Enter the number of rows: "))
    arr = []
    for i in range(rows):
        row = list(map(int, input(f"Enter the numbers for row {i+1} separated by spaces: ").split()))
        arr.append(row)
    return np.array(arr)

def get_non_corner_elements(arr):
    return arr[1:-1, 1:-1].flatten()


array = get_user_input()


non_corner_elements = get_non_corner_elements(array)


print("Non-corner elements in the array are:", non_corner_elements)


Enter the number of rows:  4
Enter the numbers for row 1 separated by spaces:  -3
Enter the numbers for row 2 separated by spaces:  4
Enter the numbers for row 3 separated by spaces:  -6
Enter the numbers for row 4 separated by spaces:  3


Non-corner elements in the array are: []


In [ ]:
# 6. WAP that takes two 2d numpy arrays as input and returns a new array containing the elements that are common to both arrays

In [35]:
import numpy as np

def get_user_input():
    rows1 = int(input("Enter the number of rows for the first array: "))
    arr1 = []
    for i in range(rows1):
        row = list(map(int, input(f"Enter the numbers for row {i+1} of the first array separated by spaces: ").split()))
        arr1.append(row)
    
    rows2 = int(input("Enter the number of rows for the second array: "))
    arr2 = []
    for i in range(rows2):
        row = list(map(int, input(f"Enter the numbers for row {i+1} of the second array separated by spaces: ").split()))
        arr2.append(row)
    
    return np.array(arr1), np.array(arr2)

def find_common_elements(arr1, arr2):
    return np.intersect1d(arr1, arr2)


array1, array2 = get_user_input()

common_elements = find_common_elements(array1, array2)


print("Common elements in the two arrays are:", common_elements)


Enter the number of rows for the first array:  2
Enter the numbers for row 1 of the first array separated by spaces:  1 2 3
Enter the numbers for row 2 of the first array separated by spaces:  4 5 6
Enter the number of rows for the second array:  2
Enter the numbers for row 1 of the second array separated by spaces:  3 4 5
Enter the numbers for row 2 of the second array separated by spaces:  6 7 8


Common elements in the two arrays are: [3 4 5 6]


In [ ]:
# 7. WAP that takes a 2d numpy array and a threshold value as input and returns 
# a new array where any element greater than the threshold is replaced with the threshold value

In [31]:
import numpy as np

def get_user_input():
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    print("Enter elements for the array:")
    arr = []
    for i in range(rows):
        row = list(map(int, input(f"Enter the numbers for row {i+1} separated by spaces: ").split()))
        if len(row) != cols:
            print("Error: Number of elements in each row must match the number of columns.")
            return None, None
        arr.append(row)
    threshold = int(input("Enter the threshold value: "))
    return np.array(arr), threshold

def replace_with_threshold(arr, threshold):
    return np.where(arr > threshold, threshold, arr)


array, threshold = get_user_input()
if array is not None:

    new_array = replace_with_threshold(array, threshold)

    print("New array after replacing elements greater than threshold:")
    print(new_array)


Enter the number of rows:  2
Enter the number of columns:  3


Enter elements for the array:


Enter the numbers for row 1 separated by spaces:  1 2 3
Enter the numbers for row 2 separated by spaces:  4 5 6
Enter the threshold value:  3


New array after replacing elements greater than threshold:
[[1 2 3]
 [3 3 3]]


In [ ]:
# 8. Write a Python program that takes a square matrix as input from the user and prints the sum of the elements located below the main diagonal.

In [29]:
def get_user_input():
    size = int(input("Enter the size of the square matrix: "))
    print("Enter the elements of the square matrix:")
    matrix = []
    for i in range(size):
        row = list(map(int, input(f"Enter the numbers for row {i+1} separated by spaces: ").split()))
        if len(row) != size:
            print("Error: Number of elements in each row must match the size of the matrix.")
            return None
        matrix.append(row)
    return matrix

def sum_below_main_diagonal(matrix):
    total_sum = 0
    for i in range(len(matrix)):
        for j in range(i):
            total_sum += matrix[i][j]
    return total_sum


matrix = get_user_input()
if matrix is not None:
  
    diagonal_sum = sum_below_main_diagonal(matrix)

    print("Sum of elements below the main diagonal:", diagonal_sum)


Enter the size of the square matrix:  3


Enter the elements of the square matrix:


Enter the numbers for row 1 separated by spaces:  1 2 3
Enter the numbers for row 2 separated by spaces:  4 5 6
Enter the numbers for row 3 separated by spaces:  7 8 9


Sum of elements below the main diagonal: 19


In [ ]:
#9. Write a Python program that takes a two-dimensional NumPy array as input from the user and prints the frequencies of each unique element in the array .

In [37]:
import numpy as np

def count_frequencies(arr):
    unique_elements, counts = np.unique(arr, return_counts=True)
    frequency_dict = dict(zip(unique_elements, counts))
    return frequency_dict

def main():
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))

    print("Enter the elements of the array row by row:")
    arr = []
    for _ in range(rows):
        row = list(map(int, input().split()))
        arr.append(row)

    array = np.array(arr)

    print("Input Array:")
    print(array)

    frequencies = count_frequencies(array)
    print("Frequencies of each unique element:")
    print(frequencies)

if __name__ == "__main__":
    main()


Enter the number of rows:  3
Enter the number of columns:  3


Enter the elements of the array row by row:


 1 2 3
 1 2 3
 4 5 6


Input Array:
[[1 2 3]
 [1 2 3]
 [4 5 6]]
Frequencies of each unique element:
{1: 2, 2: 2, 3: 2, 4: 1, 5: 1, 6: 1}


In [ ]:
# 10. WAP to create a 2d numpy array of armstrong numbers (array size given by user)

In [ ]:
import numpy as np

def is_armstrong(num):
    # Calculate the number of digits
    num_str = str(num)
    num_digits = len(num_str)
    
    # Calculate the sum of digits raised to the power of the number of digits
    armstrong_sum = sum(int(digit)**num_digits for digit in num_str)
    
    # Check if the number is Armstrong
    return armstrong_sum == num

def generate_armstrong_numbers(row, col):
    armstrong_numbers = []
    num = 1
    while len(armstrong_numbers) < row * col:
        if is_armstrong(num):
            armstrong_numbers.append(num)
        num += 1
    return np.array(armstrong_numbers).reshape(row, col)

def main():
    row = int(input("Enter the number of rows: "))
    col = int(input("Enter the number of columns: "))

    armstrong_array = generate_armstrong_numbers(row, col)

    print("2D NumPy Array of Armstrong Numbers:")
    print(armstrong_array)

if __name__ == "__main__":
    main()
